services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        ports:
            - "5432:5432"
        networks:
            - mynetwork
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
networks:
    mynetwork:
        driver: bridge
